spring:
  ai:
    openai:
      api-key:
  application:
    name: interview
  datasource:
    url: jdbc:postgresql://localhost:5432/interview
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

