spring:
  ai:
    openai:
      api-key:
  application:
    name: interview
  datasource:
    url: jdbc:postgresql://localhost:5432/interview
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

logging:
  level:
    root: INFO
    org:
      hibernate:
        SQL: DEBUG
      type:
        descriptor:
          sql:
            BasicBinder: TRACE

